### ISSUE TITLE
Internal server error, for (POST) [/users/create]

### ISSUE THREAD

**Issue by krlsBC** [pjay/plush#1]
Hi!

I´ve just try to install this on my server, I follow the next steps:

1.- Clone repository
2.-  sbt clean compile stage
3.- target/start
4.- Go to server:9000/user/add

When I try to create a user I get the following error:

```
[error] play - Cannot invoke the action, eventually got an error: java.lang.RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class models.User$
[error] application -

! @6e8i2cn3o - Internal server error, for (POST) [/users/create] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class models.User$]]
        at play.api.Application$class.handleError(Application.scala:289) ~[play_2.10-2.1.0.jar:2.1.0]
        at play.api.DefaultApplication.handleError(Application.scala:383) [play_2.10-2.1.0.jar:2.1.0]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$handleAction$1$4$$anonfun$apply$28.apply(PlayDefaultUpstreamHandler.scala:391) [play_2.10-2.1.0.jar:2.1.0]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$handleAction$1$4$$anonfun$apply$28.apply(PlayDefaultUpstreamHandler.scala:391) [play_2.10-2.1.0.jar:2.1.0]
        at scala.Option.map(Option.scala:145) [scala-library.jar:na]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$handleAction$1$4.apply(PlayDefaultUpstreamHandler.scala:391) [play_2.10-2.1.0.jar:2.1.0]
java.lang.RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class models.User$
        at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:222) ~[play_2.10-2.1.0.jar:2.1.0]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:109) ~[play_2.10-2.1.0.jar:2.1.0]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:109) ~[play_2.10-2.1.0.jar:2.1.0]
        at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[play_2.10-2.1.0.jar:2.1.0]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:108) ~[play_2.10-2.1.0.jar:2.1.0]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:106) ~[play_2.10-2.1.0.jar:2.1.0]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class models.User$
        at controllers.Users$$anonfun$create$1$$anonfun$apply$6.apply(Users.scala:67) ~[plush_2.10-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at controllers.Users$$anonfun$create$1$$anonfun$apply$6.apply(Users.scala:65) ~[plush_2.10-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at play.api.data.Form$$anonfun$fold$1.apply(Form.scala:134) ~[play_2.10-2.1.0.jar:2.1.0]
        at scala.Option.map(Option.scala:145) [scala-library.jar:na]
        at play.api.data.Form.fold(Form.scala:134) ~[play_2.10-2.1.0.jar:2.1.0]
        at controllers.Users$$anonfun$create$1.apply(Users.scala:63) ~[plush_2.10-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
```

Thanks in advance!

**Comment by pjay** [comment]
Hi,
- Do you have a redis-server running locally on port 6379 (host/port can be changed in app/models/RedisModel.scala)?
- What error do you get when you run the app in dev mode? ($ play ~run)

Thanks for trying out plush. Don't hesitate to let me know what you think about it.

**Comment by krlsBC** [comment]
What a rookie's mistake! Where was info suppose to be stored?   ( ¬_¬)

I´ve just install redis on my server and was able to add users and Apps, I´ll spend the afternoon playing with it.

When running with play 2.1.1 I get this error:

```
[info] Loading project definition from /opt/play-2.1.1/plush/project

This project uses Play 2.1.0!
Update the Play sbt-plugin version to 2.1.1 (usually in project/plugins.sbt)

[info] Set current project to plush (in build file:/opt/play-2.1.1/plush/)

[info] Updating {file:/opt/play-2.1.1/plush/}plush...
[warn]  [NOT FOUND  ] org.slf4j#slf4j-api;1.6.6!slf4j-api.jar (5ms)          
[warn] ==== local: tried
[warn]   /opt/play/repository/local/org.slf4j/slf4j-api/1.6.6/jars/slf4j-api.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::              FAILED DOWNLOADS            ::
[warn]  :: ^ see resolution messages for details  ^ ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.slf4j#slf4j-api;1.6.6!slf4j-api.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: download failed: org.slf4j#slf4j-api;1.6.6!slf4j-api.jar
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:214)
    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:122)
    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:121)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:114)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:114)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:102)
    .
    .
    .
[error] (*:update) sbt.ResolveException: download failed: org.slf4j#slf4j-api;1.6.6!slf4j-api.jar
```

But maybe this should be on other issue.

Thanks again!

**Comment by pjay** [comment]
Thanks for the info, I'll upgrade to Play 2.1.1 in the next days and see how to fix this issue.
